// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif


RcppExport SEXP _rcpp_module_boot_stan_fit4AugBin2T1A_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4BebopInPeps2_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4CrmEmpiricNormalPrior_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4CrmOneParamLogisticGammaPrior_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4CrmOneParamLogisticNormalPrior_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4CrmTwoParamLogisticNormalPrior_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4EffTox_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4NeuenschwanderTwoParamLogit_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4ThallHierarchicalBinary_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4AugBin2T1A_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4AugBin2T1A_mod, 0},
    {"_rcpp_module_boot_stan_fit4BebopInPeps2_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4BebopInPeps2_mod, 0},
    {"_rcpp_module_boot_stan_fit4CrmEmpiricNormalPrior_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4CrmEmpiricNormalPrior_mod, 0},
    {"_rcpp_module_boot_stan_fit4CrmOneParamLogisticGammaPrior_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4CrmOneParamLogisticGammaPrior_mod, 0},
    {"_rcpp_module_boot_stan_fit4CrmOneParamLogisticNormalPrior_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4CrmOneParamLogisticNormalPrior_mod, 0},
    {"_rcpp_module_boot_stan_fit4CrmTwoParamLogisticNormalPrior_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4CrmTwoParamLogisticNormalPrior_mod, 0},
    {"_rcpp_module_boot_stan_fit4EffTox_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4EffTox_mod, 0},
    {"_rcpp_module_boot_stan_fit4NeuenschwanderTwoParamLogit_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4NeuenschwanderTwoParamLogit_mod, 0},
    {"_rcpp_module_boot_stan_fit4ThallHierarchicalBinary_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4ThallHierarchicalBinary_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_trialr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
